stages:
  - build

image: alpine

pages:
  script:
  - apk update && apk add doxygen
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


build_a:
  stage: build
  script:
    - echo "This job builds something quickly."
